name: "codeit-backend-dev"
services:
  codeit-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - ./worker:/worker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data-codeit:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q check_running"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres-data-codeit:
